// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-TdUIJAp6K7KFFKWxpkShweUwB5_OK4M',
    appId: '1:401585156208:web:231847d164358a47ae84b5',
    messagingSenderId: '401585156208',
    projectId: 'firebase-auth-cwancu',
    authDomain: 'fir-auth-cwancu.firebaseapp.com',
    storageBucket: 'firebase-auth-cwancu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdIXyS1m0J2xUrcizwcHPQz5chU-fsSU0',
    appId: '1:401585156208:android:fc48f17001444464ae84b5',
    messagingSenderId: '401585156208',
    projectId: 'firebase-auth-cwancu',
    storageBucket: 'firebase-auth-cwancu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzFlDmjC0xNPt4nLTpN2GML8T-EaXmg94',
    appId: '1:401585156208:ios:66fc4611dad8bc0aae84b5',
    messagingSenderId: '401585156208',
    projectId: 'firebase-auth-cwancu',
    storageBucket: 'firebase-auth-cwancu.appspot.com',
    iosClientId: '401585156208-u0jrtkk5kuhekfmvr76k562qh3jlhl4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzFlDmjC0xNPt4nLTpN2GML8T-EaXmg94',
    appId: '1:401585156208:ios:66fc4611dad8bc0aae84b5',
    messagingSenderId: '401585156208',
    projectId: 'firebase-auth-cwancu',
    storageBucket: 'firebase-auth-cwancu.appspot.com',
    iosClientId: '401585156208-u0jrtkk5kuhekfmvr76k562qh3jlhl4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );
}
