// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4svya8wSfnDUlmZe91sEziNAZDMJ_uo0',
    appId: '1:1055779107353:web:9dd106fc71350839f27088',
    messagingSenderId: '1055779107353',
    projectId: 'firebase-my-auth',
    authDomain: 'fir-my-auth-e6dc2.firebaseapp.com',
    storageBucket: 'firebase-my-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzd0C5SJYTHC3GRetEmMxT3zxvRI3Ots',
    appId: '1:1055779107353:android:6ebc3fd2f4bafb24f27088',
    messagingSenderId: '1055779107353',
    projectId: 'firebase-my-auth',
    storageBucket: 'firebase-my-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYSwspF-4FpE6Y4ixhXuhvF2enzw3n_WQ',
    appId: '1:1055779107353:ios:399a18dc72c2e4aef27088',
    messagingSenderId: '1055779107353',
    projectId: 'firebase-my-auth',
    storageBucket: 'firebase-my-auth.appspot.com',
    iosClientId: '1055779107353-4otia0q7i1194utsunjl4hona1q08pkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYSwspF-4FpE6Y4ixhXuhvF2enzw3n_WQ',
    appId: '1:1055779107353:ios:399a18dc72c2e4aef27088',
    messagingSenderId: '1055779107353',
    projectId: 'firebase-my-auth',
    storageBucket: 'firebase-my-auth.appspot.com',
    iosClientId: '1055779107353-4otia0q7i1194utsunjl4hona1q08pkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );
}
