// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNo3yvXrD6905Jnvpuuz0DCq9njRd-1Lk',
    appId: '1:837111026262:web:a0f302583d3be9df8ce1f7',
    messagingSenderId: '837111026262',
    projectId: 'firebase-cwancu',
    authDomain: 'fir-cwancu.firebaseapp.com',
    storageBucket: 'firebase-cwancu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm5Qkk9-rhxOu48ezh8jJPzVTwxI2ozPY',
    appId: '1:837111026262:android:6d05eca125ccd6ab8ce1f7',
    messagingSenderId: '837111026262',
    projectId: 'firebase-cwancu',
    storageBucket: 'firebase-cwancu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDw-B6zoObmhBz6-v9rK6PDhPszXkk3dw',
    appId: '1:837111026262:ios:a8c3db92c3de93118ce1f7',
    messagingSenderId: '837111026262',
    projectId: 'firebase-cwancu',
    storageBucket: 'firebase-cwancu.appspot.com',
    iosClientId: '837111026262-hapic3u1kdo5vmg8fn5nqcap9f2g8u95.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDw-B6zoObmhBz6-v9rK6PDhPszXkk3dw',
    appId: '1:837111026262:ios:a8c3db92c3de93118ce1f7',
    messagingSenderId: '837111026262',
    projectId: 'firebase-cwancu',
    storageBucket: 'firebase-cwancu.appspot.com',
    iosClientId: '837111026262-hapic3u1kdo5vmg8fn5nqcap9f2g8u95.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProjects',
  );
}
